trigger:
- develop
- master
- feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Rust@1
  inputs:
    installNightly: false
  displayName: 'Install rust stable'
- task: Cargo@1
  inputs:
    cargoCommand: 'test'
    cargoCommandOptions: '--release'
    verbose: true
  displayName: Test the binary
- task: Cargo@1
  inputs:
    cargoCommand: 'build'
    cargoCommandOptions: '--release'
    verbose: true
  displayName: Build the binary
- task: CmdLine@2
  inputs:
    script: |
      strip $(Build.Repository.LocalPath)/target/release/jaesve
  displayName: Strip the binary
- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.Repository.LocalPath)/target/release/jaesve'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: 'f8625b77-e77e-48a4-9569-1570ad4bb9c8'
    versionOption: 'patch'
  displayName: Deploy the binary
