[package]
name = "jaesve"
version = "0.9.1"
authors = ["Baz <github(a)luxolus.com>"]
edition = "2018"
description = "Utility for converting JSON into a CSV-like format"

[dependencies]
serde_json = "1.0.39"
failure = "0.1.5"
clap = "2.33.0"
structopt = "0.2.15"
regex = "1"
